### ISSUE TITLE
Is there anyway we can get this updated for blender 2.49+

### ISSUE THREAD

**Issue by stolencatkarma** [Akaito/blender-ninjaripper-importer#1]
they changed the way addons are made after 2.50 and this no longer installs

**Comment by Akaito** [comment]
I've never played with installing custom addons in Blender.  This was always something I'd just copy-paste into a script window in Blender.  But I might look into this in the future.

@stolencatkarma, I may not have ninjaripper installed on any machine right now.  If you can provide me with some sample output ( chris@codesaru.com ), it'd lower resistance to getting this changed and tested.

And thanks for letting me know.  :)

**Comment by Akaito** [comment]
This has been updated to be an installable Blender addon, which adds the menu item File -> Import -> Ninja/DX Ripdump.  Currently only tested with Blender 2.74.  See the updated README.md for instructions.
