### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by ThunderBolt6** [Akaito/blender-ninjaripper-importer#3]
Ninjarupper 1.6 and blender 2.77

**Comment by Akaito** [comment]
Please provide some sample data for me to test this and get the plugin working.  I don't use NinjaRipper anymore.  Though if you do provide sample data, please either have it be public domain data, or e-mail it directly to me at chris@codesaru.com so non-public model data isn't out on the public Internet forever.

**Comment by ThunderBolt6** [comment]
nvm, found another plugin (a port of maya but for blender)
