### ISSUE TITLE
ninjaripper does not output txt files but rip files

### ISSUE THREAD

**Issue by phil123456** [Akaito/blender-ninjaripper-importer#4]
cant believe this issue is never looked through

**Comment by Akaito** [comment]
My plugin has no impact on what format the ninjaripper tool outputs.  Could you describe what you're after more completely?

**Comment by phil123456** [comment]
ninjaripper outputs .rip files (that are binary)
your pluggin loads .txt files
so how is this supposed to work ?

**Comment by Akaito** [comment]
Unless a more recent version of Ninja Ripper removed it, Ninja Ripper has an option to output plain-text files instead of binary .rip files.

**Comment by phil123456** [comment]
yeah removed apparently, which renders your importer obsolete

**Comment by Akaito** [comment]
Closed unless more recent Ninja Ripper versions still support a non-binary output.  Or documentation can be found for the binary format.
